2021-07-14 18:12:33,605 ERROR: Exception on /favicon.ico [GET] [in /Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1489, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1471, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/ctx.py", line 367, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2032, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1383, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1323, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/app/errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/app/templates/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/app/templates/base.html", line 53, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-07-14 18:12:36,011 ERROR: Exception on /user/quintest [GET] [in /Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/app/routes.py", line 89, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/app/templates/base.html", line 53, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-07-14 18:13:04,008 INFO: Microblog startup [in /Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/app/__init__.py:52]
2021-07-14 18:13:13,645 ERROR: Exception on / [GET] [in /Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/app/routes.py", line 37, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items,
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/app/templates/base.html", line 53, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-07-14 18:15:24,639 INFO: Microblog startup [in /Users/quinlanalexander/Documents/GradSchool/PersonalProjects/microblog/app/__init__.py:52]
